Prevent upgrade command from succeeding when brew update fails

diff --git a/bin/ih-setup b/bin/ih-setup
--- a/bin/ih-setup
+++ b/bin/ih-setup
@@ -301,21 +301,26 @@ function ih::private::state::is-step-installed() {
 }
 
 function ih::private::upgrade() {
-
   ih::log::info "Checking for updates..."
 
+  if ! brew update >/dev/null 2>&1; then
+    ih::log::error "brew update failed"
+    return 1
+  fi
+
   local OUTDATED
-  brew update >/dev/null
   OUTDATED=$(brew outdated ih-core)
   if [ -z "$OUTDATED" ]; then
     ih::log::info "ih-setup is up-to-date"
-    return 0
+  else
+    ih::log::info "Upgrading ih-setup"
+    if brew upgrade ih-core; then
+      ih-setup install
+    else
+      ih::log::error "brew upgrade ih-core failed"
+      return 1
+    fi
   fi
-
-  ih::log::info "Upgrading ih-setup"
-
-  brew upgrade ih-core || exit 1
-  ih-setup install
 }
 
 function ih::private::state::make-step-installed() {
