improved messaging based on feedback

diff --git a/bin/ih-setup b/bin/ih-setup
--- a/bin/ih-setup
+++ b/bin/ih-setup
@@ -182,7 +182,7 @@ function ih::private::apply-to-steps() {
     if [[ " ${DOMAINS[*]} " =~ " "${DOMAIN}" " ]]; then
       if [[ " ${IH_SETUP_STEPS[*]} " =~ " "${STEP}" " ]]; then
         if ! "ih::private::$COMMAND" "$STEP"; then
-          ih::log::error "Command $COMMAND failed for step $STEP"
+          ih::log::error "Command $COMMAND failed for step $STEP. Re-run using 'ih-setup -v install' for more details."
           exit 1
         fi
 
@@ -283,7 +283,7 @@ function ih::private::upgrade() {
 
   ih::log::info "Upgrading ih-setup"
 
-  brew upgrade ih-core
+  brew upgrade ih-core || exit 1
   ih-setup install
 }
 
diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -37,6 +37,23 @@ fi
 
 if command -v ih-setup; then
   ih-setup install
+  SUCCEEDED=$?
+
+  if [ $SUCCEEDED -eq 0 ]; then
+    echo "Install succeeded. You should be able to start a new shell
+and have everything work correctly."
+  else
+    echo "Install failed. Please contact platform support
+in the #developer-platform-support stream in Zulip or the #dept-eng_infra channel
+in Slack. You can also search Confluence for 'Engineer Onboarding Guide' for
+more troubleshooting tips.
+
+You don't need to run the bootstrap script again. You can
+now use 'ih-setup install' to re-try installation, or 'ih-setup check'
+to get more information."
+  fi
+
+  exit $SUCCEEDED
 else
   echo "ih-setup is not available in your PATH. Check the logs above to see if there was a fatal error,
 and make sure that /usr/local/bin is in your PATH"
