moved m1 logic to install step

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,65 +1,44 @@
 #!/bin/bash
 
-#shellcheck disable=SC2034
-
-if ! command -v brew &>/dev/null; then
-
-  if [[ $(uname -m) == 'arm64' ]]; then
-    echo '-----------------------------------
-You have an M1 chip and you are not
-running in a Rosetta-flavored shell.
-There may be a day when all our tools
-work correctly on M1, but until that day
-you will need to install them in x86
-compatibility mode. I will install brew
-in x86 compatibiility mode to support that.
-
-When you run brew commands in the future
-you may run into a message telling you
-that you need to install it in another mode.
-You can follow those instructions, or just
-make a new shell using "arch -x86_64 zsh"
-and do your brew install from there.
-
-Press any key to continue
-  '
-    read -rn 1
-    arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-  else
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
-  fi
+if ! command -v brew >/dev/null; then
+  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
 fi
 
-eval "$(/usr/local/bin/brew shellenv)"
+# Activate the correct brew for the CPU
+if [[ "$(uname -m)" == 'arm64' ]]; then
+  eval "$(/opt/homebrew/bin/brew shellenv)"
+else
+  eval "$(/usr/local/bin/brew shellenv)"
+fi
 
 echo "Installing ih-core formula..."
 echo "Sometimes the dependency downloads fail, possibly due to the VPN, so \
 I will retry installing a couple times if it fails."
 
-if [[ $1 == "local" ]]; then
-  THIS_DIR=$(dirname "$(realpath "$0")")
+brew update
+brew tap ConsultingMD/homebrew-ih-public https://github.com/ConsultingMD/homebrew-ih-public.git
 
-  for i in 1 2 3; do brew install --formula -s "$THIS_DIR/formula/ih-core.rb" && break; done
+SUCCEEDED=1
+for _ in 1 2 3; do
+  brew install ih-core
+  SUCCEEDED=$?
+  if [ $SUCCEEDED -eq 0 ]; then
+    break
+  fi
+done
 
-elif [[ ${#} -eq 1 ]]; then
-  VERSION=$1
-  echo "Installing version $VERSION"
-  TMP_DIR=$(mktemp -d)
-  FORMULA_PATH="$TMP_DIR/ih-core.rb"
-  curl -L -o "$FORMULA_PATH" "https://github.com/ConsultingMD/homebrew-ih-public/releases/download/$VERSION/ih-core.rb"
-
-  for i in 1 2 3; do brew install --formula -s "$FORMULA_PATH" && break; done
-  rm -rf "$TMP_DIR"
-else
-  brew update
-  brew tap ConsultingMD/homebrew-ih-public https://github.com/ConsultingMD/homebrew-ih-public.git
-  for i in 1 2 3; do brew install ih-core && break; done
+if [ $SUCCEEDED -eq 1 ]; then
+  echo "Install of ih-setup formula failed. Please contact platform support
+in the #developer-platform-support stream in Zulip or the #dept-eng_infra channel
+in Slack. You can also search Confluence for 'Engineer Onboarding Guide' for
+more troubleshooting tips."
+  exit 1
 fi
 
 if command -v ih-setup; then
   ih-setup install
 else
   echo "ih-setup is not available in your PATH. Check the logs above to see if there was a fatal error,
-and make sure that /usr/local/bin is in your PATH. Then run 'ih-setup install' again."
+and make sure that /usr/local/bin is in your PATH"
   exit 1
 fi
