improving logging

diff --git a/ih-core/bin/ih-setup b/ih-core/bin/ih-setup
--- a/ih-core/bin/ih-setup
+++ b/ih-core/bin/ih-setup
@@ -6,6 +6,7 @@ export IH_CORE_LIB_DIR="$IH_CORE_DIR/lib"
 
 source "$IH_CORE_LIB_DIR/confirm.sh"
 source "$IH_CORE_LIB_DIR/colors.sh"
+source "$IH_CORE_LIB_DIR/log.sh"
 
 # Attempts to return help for the step passed as an argument
 function ih::private::step-help() {
@@ -36,10 +37,9 @@ function ih::private::step-install() {
     fi
 }
 
-
 function ih::private::try-invoke() {
     if [[ $# -ne 2 ]]; then
-        red "ih::private::try-invoke takes arguments STEP COMMAND"
+        ih::log::error "ih::private::try-invoke takes arguments STEP COMMAND"
         return 1
     fi
     local STEP=$1
@@ -49,7 +49,7 @@ function ih::private::try-invoke() {
         code=$?
         return $code
     else
-        red "Step $1 does not implement command $2"
+        ih::log::error "Step $1 does not implement command $2"
         return 1
     fi
 }
@@ -60,13 +60,11 @@ function ih::private::try-invoke() {
 # Otherwise it invokes the function, and echoes it's output,
 # and returns the result.
 function ih::private::step-test() {
-    local RESULT_TEXT
     local RESULT
 
     if typeset -f ih::setup::$1::test >/dev/null; then
-        RESULT_TEXT=$(ih::setup::$1::test)
+        ih::setup::$1::test
         RESULT=$?
-        echo $RESULT_TEXT
         return $RESULT
     else
         echo "Step $1 does not implement a test method"
@@ -111,7 +109,6 @@ function ih::private::load-steps() {
     done
 }
 
-
 function ih::private::apply-to-steps() {
     local COMMAND=$1
     shift
@@ -125,7 +122,7 @@ function ih::private::apply-to-steps() {
 }
 
 function ih::private::describe-step() {
-    blue "--------- $1 -----------"
+    blue "--------- $1 -----------\n"
     ih::private::step-help "$1"
     echo ""
     echo "depends on: $(ih::private::step-deps $1)"
@@ -133,12 +130,17 @@ function ih::private::describe-step() {
 }
 
 function ih::private::test-step() {
-    ih::private::step-test "$STEP" >/dev/null
+    ih::log::debug "Testing step $STEP..."
+    if [[ $IH_DEBUG = "1" ]]; then
+        ih::private::step-test "$STEP"
+    else
+        ih::private::step-test "$STEP" >/dev/null
+    fi
     TEST_CODE=$?
     if [[ $TEST_CODE = 0 ]]; then
-        green "$STEP has been installed"
+        green "$STEP has been installed\n"
     else
-        red "$STEP needs to be installed"
+        red "$STEP needs to be installed\n"
     fi
 }
 
@@ -148,14 +150,14 @@ function ih::private::test-deps() {
     local DEP
     local DEPS=$(ih::private::try-invoke $1 deps)
     for DEP in $DEPS; do
-        ih::private::step-test "$DEP" > /dev/null
+        ih::private::step-test "$DEP" >/dev/null
         TEST_CODE=$?
         if [[ $TEST_CODE != 0 ]]; then
-            red "$DEPTH Dependency $DEP not installed"
+            red "$DEPTH Dependency $DEP not installed\n"
             FAILED=1
-        else 
-            green "$DEPTH Dependency $DEP is installed"
-        fi 
+        else
+            green "$DEPTH Dependency $DEP is installed\n"
+        fi
         ih::private::test-deps "$DEP" "$DEPTH"
         TEST_CODE=$?
         if [[ $TEST_CODE != 0 ]]; then
@@ -178,25 +180,25 @@ function ih::private::test-deps() {
 function ih::private::install-step() {
     local TEST_CODE
     if [ "$IH_FORCE" != "1" ]; then
-        # gray "Checking whether step $STEP needs to be installed..."
-        ih::private::step-test "$STEP" > /dev/null
+        ih::log::debug "Checking whether step $STEP needs to be installed..."
+        ih::private::step-test "$STEP" >/dev/null
         TEST_CODE=$?
         if [[ $TEST_CODE -eq 0 ]]; then
-            gray "${STEP} has been installed (use --force to re-install)"
+            ih::log::info "${STEP} has been installed (use --force to re-install)"
             return 0
         fi
 
-        ih::private::test-deps "$STEP" > /dev/null
+        ih::private::test-deps "$STEP" >/dev/null
         TEST_CODE=$?
         if [[ $TEST_CODE -ne 0 ]]; then
-            red "$STEP dependencies have not been installed (use --force to ignore)"
-            ih::private::test-deps "$STEP" 
+            red "$STEP dependencies have not been installed (use --force to ignore)\n"
+            ih::private::test-deps "$STEP"
             return 1
         fi
 
     fi
 
-    blue "Planning to install step $STEP..."
+    ih::log::info "Planning to install step $STEP..."
 
     if [ "$IH_NO_CONFIRM" != "1" ]; then
 
@@ -208,7 +210,7 @@ function ih::private::install-step() {
         ih::private::confirm "$CONFIRM_TEXT"
         CONFIRMED_STEP=$?
         if [[ $CONFIRMED_STEP -ne 0 ]]; then
-            yellow "Skipping step $STEP"
+            yellow "Skipping step $STEP\n"
             return 0
         fi
     fi
@@ -217,9 +219,9 @@ function ih::private::install-step() {
 
     SUCCCESS=$?
     if [[ $SUCCCESS -eq 0 ]]; then
-        green "Installed step $STEP"
+        green "Installed step $STEP\n"
     else
-        red "💩 Installation of step $STEP failed"
+        ih::log::error "💩 Installation of step $STEP failed"
         return 1
     fi
 }
@@ -256,6 +258,7 @@ $subcommand"
  Global flags:
     -f    Force command even if heuristics indicate it's not needed
     -y    Don't prompt for confirmation
+    -v    Verbose logging
 
 USAGE
 }
@@ -267,14 +270,19 @@ function main() {
         exit 0
     fi
 
-    for arg; do
-        if [[ $arg == "-y" ]]; then
-            IH_NO_CONFIRM=1
-        fi
-        if [[ $arg == "-f" ]]; then
-            IH_FORCE=1
-        fi
+    while getopts "yfv" arg; do
+        case $arg in
+        y) export IH_NO_CONFIRM=1 ;;
+        f) export IH_FORCE=1 ;;
+        v) export IH_DEBUG=1 ;;
+        *)
+            ih::help
+            exit 1
+            ;;
+        esac
     done
+
+    shift $(($OPTIND - 1))
 
     local IS_AUGMENT_SOURCED_IN_SHELL
     if [[ $IH_AUGMENT_SOURCED = "yes" ]]; then
@@ -298,7 +306,7 @@ function main() {
         ih::private::apply-to-steps install-step "$*"
         RESULT=$?
         if [[ -z $IS_AUGMENT_SOURCED_IN_SHELL ]]; then
-            yellow "Remember to source .zshrc or .bashrc to add IH augments to your shell"
+            ih::log::warn "Remember to source .zshrc or .bashrc to add IH augments to your shell"
         fi
         return $?
         ;;
